const widget = new ListWidget();
let currency = "人民币";
const url = "https://www.hanshanmoney.com/zh/rate-cn/";
const req = new Request(url);
const reqdata = await req.loadString();
const data = reqdata.replace(/<[^>]+>/g,'');
const riqi = data.match(/有效日期:.*/i)?.toString().replace(/ /g,'') || "日期信息不可用";
const shijian = data.match(/更新时间:.*/i)?.toString().replace(/ /g,'') || "时间信息不可用";
const huilvMatch = data.match(new RegExp(currency + '.*\n.*', 'i'));
const huilv = huilvMatch?.toString().replace(/\n     /g, '') || "汇率信息不可用";
const titleText = widget.addText("汉生汇率");
titleText.centerAlignText();
widget.addSpacer(15);
const stack = widget.addStack();
stack.layoutVertically();
stack.addText(riqi);
stack.addSpacer(5);
stack.addText(shijian);
stack.addSpacer(5);
stack.addText(huilv);
Script.setWidget(widget);
Script.complete();